function C = ComputeC(th1,th2,thd1,thd2)
%COMPUTEC
%    C = COMPUTEC(TH1,TH2,THD1,THD2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Feb-2021 00:36:32

t2 = sin(th2);
C = reshape([t2.*thd2.*-2.0,t2.*thd1.*2.0,t2.*(thd1+thd2).*-2.0,0.0],[2,2]);
