function G = ComputeG(th1,th2)
%COMPUTEG
%    G = COMPUTEG(TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Feb-2021 14:41:10

t2 = th1+th2;
t3 = cos(t2);
t4 = t3.*(9.81e+2./1.0e+2);
G = [t4+cos(th1).*2.943e+1;t4];
