function gth = ComputeFK(th1,th2)
%COMPUTEFK
%    GTH = COMPUTEFK(TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    23-Feb-2021 14:41:10

t2 = cos(th1);
t3 = sin(th1);
t4 = th1+th2;
t5 = t2.*2.0;
t6 = t3.*2.0;
t7 = cos(t4);
t8 = sin(t4);
t9 = -t3;
t10 = -t8;
gth = reshape([t2,t3,0.0,0.0,t9,t2,0.0,0.0,0.0,0.0,1.0,0.0,t5,t6,0.0,1.0,t7,t8,0.0,0.0,t10,t7,0.0,0.0,0.0,0.0,1.0,0.0,t5+t7.*2.0,t6+t8.*2.0,0.0,1.0,t2,t3,0.0,0.0,t9,t2,0.0,0.0,0.0,0.0,1.0,0.0,t2,t3,0.0,1.0,t7,t8,0.0,0.0,t10,t7,0.0,0.0,0.0,0.0,1.0,0.0,t5+t7,t6+t8,0.0,1.0],[4,4,2,2]);
